name: main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          target_folder: './content-badges'
          label: ' '
          message: 'shields.io'
          logo: 'githubpages'
          color: 'blue'
